pipeline {
  agent any
  stages {
    stage('Precheck') {
      steps {
        sh '''
				echo ORACLE_HOME=${ORACLE_HOME}
				echo PATH=${PATH}
				whoami
				which git
				#which expdp
				git --version
				git config --global user.email "jenkins@datical.com"
				git config --global user.name "jenkins"
			'''
      }
    }



            stage('Provision') {
              steps {
                sh '''
					  { set +x; } 2>/dev/null
											  
					  cd ${PROJ_DDB}
					  PATH=/home/delphix_os/DaticalDB/repl:${PATH}
cd /opt/datical/dxtoolkit2
./dx_provision_vdb -engine delphix-vm-n-6 -type oracle -group Oracle_Targets -sourcename orcl -targetname orcl_ref -environment "172.16.129.133" -envinst "/u01/app/oracle/product/11.2.0.4/db_1" -template 200M -dbname orcl_ref -mntpoint /mnt/provision -autostart yes            
					  '''
              }
            }

          }
          environment {
            GITURL = 'git@github.com:duckback00'
            GIT_DATICAL_REPO = 'epod_datical'
            GIT_SQL_REPO = 'epod_sql'
            PROJ_DDB = 'epod_datical'
            PROJ_SQL = 'epod_sql'
            DATICAL_PIPELINE = 'current'
            BRANCH = 'current'
            RELEASE_LABEL = "${BUILD_NUMBER}"
            ORACLE_HOME = '/opt/oracle/product/12.1/client'
            PATH = "$PATH:/home/delphix_os/DaticalDB/repl:$ORACLE_HOME/bin"
          }
          post {
            always {
              archiveArtifacts '**/daticaldb.log, **/Reports/**, **/Logs/**, **/Snapshots/** ,**/*.zip'
            }

          }
        }
