pipeline {
  agent any
  stages {
    stage('Precheck') {
      steps {
        sh '''
			echo ORACLE_HOME=${ORACLE_HOME}
			echo PATH=${PATH}
			whoami
			which git
			#which expdp
			git --version
			git config --global user.email "jenkins@datical.com"
			git config --global user.name "jenkins"
		'''
      }
    }

    stage('Delete') {
      steps {
        sh '''
			{ set -x; } 2>1   ###/dev/null
								  
			###cd ${PROJ_DDB}
			PATH=/home/delphix_os/DaticalDB/repl:${PATH}
			RESULTS=`/opt/datical/dxtoolkit2/dx_get_db_env -engine delphix-vm-n-6 -name orcl --format json | jq length 2>/dev/null`
			echo "Results: ${RESULTS}"
			if [[ "${RESULTS}" != "" ]]
                        then
				/opt/datical/dxtoolkit2/dx_remove_db -engine delphix-vm-n-6 -name orcl_ref -skip 
			fi
			RESULTS=`/opt/datical/dxtoolkit2/dx_get_db_env -engine delphix-vm-n-6 -name orcl --format json | jq length 2>/dev/null`
			echo "Results: ${RESULTS}"
			if [[ "${RESULTS}" != "" ]]
                        then
				/opt/datical/dxtoolkit2/dx_remove_db -engine delphix-vm-n-6 -name orcl -skip 
			fi
			RESULTS=`/opt/datical/dxtoolkit2/dx_get_env -engine delphix-vm-n-6 -name 172.16.129.133 --format json | jq ".results[] | length"`
			echo "Results: ${RESULTS}"
			if [[ "${RESULTS}" != "" ]]
                        then				
				/opt/datical/dxtoolkit2/dx_remove_env -engine delphix-vm-n-6 -name 172.16.129.133 -skip 
			fi

                    '''
      }
    }

  }
  environment {
    GITURL = 'git@github.com:duckback00'
    GIT_DATICAL_REPO = 'epod_datical'
    GIT_SQL_REPO = 'epod_sql'
    PROJ_DDB = 'epod_datical'
    PROJ_SQL = 'epod_sql'
    DATICAL_PIPELINE = 'current'
    BRANCH = 'current'
    RELEASE_LABEL = "${BUILD_NUMBER}"
    ORACLE_HOME = '/opt/oracle/product/12.1/client'
    PATH = "$PATH:/home/delphix_os/DaticalDB/repl:$ORACLE_HOME/bin"
  }
}
